version: 2.1

# Use 'setup_remote_docker' if you need to build or use Docker commands
jobs:
  build-and-test:
    docker:
      - image: woytekn1/playwright-allure-awscli:latest # Use your Docker image
        auth: # Use Docker Hub credentials if necessary
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID} # Set these in CircleCI project settings or context
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: "eu-central-1" # Default region for AWS CLI
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7 # Use a specific version of Docker if necessary
      - run:
          name: "Execute Tests"
          command: |
            echo "Running tests and other commands inside Docker..."
            docker run --rm \
              -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
              -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
              -e AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION} \
              woytekn1/playwright-allure-awscli:latest  # Replace with your actual image name

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-and-test
