version: 2.1
executors:
  docker-executor:
    docker:
      - image: mcr.microsoft.com/playwright:v1.37.0-jammy
jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - '79:9c:29:d1:fe:a1:65:4e:e9:5b:25:f9:8f:d6:ea:07'
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Install Allure Commandline
          command: npm install -g allure-commandline
      - run:
          name: Install Java
          command: |
            apt-get update
            apt-get install -y openjdk-11-jdk
      - run:
          name: Set JAVA_HOME
          command: echo 'export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"' >> $BASH_ENV
      - run:
          name: Update PATH
          command: echo 'export PATH="$JAVA_HOME/bin:$PATH"' >> $BASH_ENV
      - run:
          name: Run Playwright Tests
          command: npm test
      - run:
          name: Generate Allure Report
          command: allure generate --clean
      - run:
          name: Copy Allure Report to AWS
          command: |
            scp -r -o StrictHostKeyChecking=no allure-report ec2-user@ec2-13-48-105-76.eu-north-1.compute.amazonaws.com:/var/www/allure-reports/
