version: 2.1
executors:
  docker-executor:
    docker:
      - image: woytekn1/playwright-allure-awscli:latest # Nazwa obrazu, który stworzyłeś
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout # Pobiera kod źródłowy
      - add_ssh_keys:
          fingerprints:
            - "9b:03:91:c2:5a:d9:6e:55:2a:5a:5c:39:49:8b:43:97"
      - run:
          name: Define Timestamp
          command: echo 'export TIMESTAMP=$(date +%Y%m%d%H%M%S)' >> $BASH_ENV
      - run:
          name: Run Playwright Tests
          command: npm test # Uruchom testy z Playwright
      - run:
          name: Generate Allure Report with History
          command: allure generate allure-results --clean
      - run:
          name: Upload New Allure Report to S3 with Timestamp
          command: |
            UNIQUE_REPORT_DIR="build-$(echo $CIRCLE_BUILD_NUM)-${TIMESTAMP}"
            aws s3 sync ./allure-report s3://allure-poc-wojtek/allure-reports/$UNIQUE_REPORT_DIR --acl public-read
      - run:
          name: Update Latest Report Reference with History
          command: |
            aws s3 rm s3://allure-poc-wojtek/allure-reports/latest --recursive
            aws s3 cp --recursive ./allure-report s3://allure-poc-wojtek/allure-reports/latest/
            aws s3 cp --recursive ./allure-report/history s3://allure-poc-wojtek/allure-reports/latest/history/
      - run:
          name: Create Allure Report URL File
          command: |
            echo "Allure report is available at https://allure-poc-wojtek.s3.eu-central-1.amazonaws.com/allure-reports/${UNIQUE_REPORT_DIR}/index.html" > allure-report-url.txt
      - store_artifacts:
          path: allure-report-url.txt
          destination: allure-report-url

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
