version: 2.1
executors:
  docker-executor:
    docker:
      - image: mcr.microsoft.com/playwright:v1.37.0-jammy
jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - '9b:03:91:c2:5a:d9:6e:55:2a:5a:5c:39:49:8b:43:97'
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Install Allure Commandline
          command: npm install -g allure-commandline
      - run:
          name: Install Java
          command: |
            apt-get update
            apt-get install -y openjdk-11-jdk
      - run:
          name: Set JAVA_HOME
          command: echo 'export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"' >> $BASH_ENV
      - run:
          name: Update PATH
          command: echo 'export PATH="$JAVA_HOME/bin:$PATH"' >> $BASH_ENV
      - run:
          name: Run Playwright Tests
          command: npm test
      - run:
          name: Generate Allure Report
          command: allure generate allure-results --clean -o allure-report
      - run:
          name: Copy Allure Report to AWS
          command: |
            scp -r -o StrictHostKeyChecking=no allure-report ec2-user@ec2-16-16-68-191.eu-north-1.compute.amazonaws.com:/var/www/allure-reports/
      - run:
          name: Verify Files on AWS
          command: |
            ssh -o StrictHostKeyChecking=no ec2-user@ec2-16-16-68-191.eu-north-1.compute.amazonaws.com 'ls -l /var/www/allure-reports/'s
      - run:
          name: Display Allure Report URL
          command: echo "Allure report is available at http://ec2-16-16-68-191.eu-north-1.compute.amazonaws.com/allure-reports"
